input_file: data/preference_data/preference_data_hf
output_folder: outputs/rl_model

TEST_SIZE: 0.2
RANDOM_STATE: 32
use_unsloth: True
use_instruct: True
device: cuda

training_config: 
  num_epochs: 20
  learning_rate: 0.00005
  batch_size: 32
  max_length: 1024
  max_prompt_length: 1024
  beta: 0.1
  model_name: unsloth/Llama-3.2-3B-Instruct

lora_config: 
  r: 8
  lora_alpha: 16
  lora_dropout: 0
  task_type: CAUSAL_LM

