input_file: data/gbv_cs.tsv
output_file: outputs/result

# https://docs.unsloth.ai/basics/llama-4-how-to-run-and-fine-tune#tutorial-how-to-run-llama-4-scout-in-llama.cpp
model_name: unsloth/Llama-3.2-3B-Instruct
# model_name: unsloth/phi-4-unsloth-bnb-4bit
# model_name: outputs/sft_model/checkpoints-unsloth_Llama-3.2-3B-Instruct-sft
# model_name: outputs/rl_model/checkpoints-unsloth_Llama-3.2-3B-Instruct-dpo

#chat_template coming from https://docs.unsloth.ai/basics/chat-templates
chat_template: llama-32 # phi-4
use_instruct: True
use_unsloth: True
device: cuda

params:
 max_new_tokens: 250
 temperature: 0.6
 top_p: 0.9


task: generate
task_prompt: simple-zero-shot-1
text_columns: ['gbv_text', 'cs_strategy'] 

batch_size: 5
random_state: 32
max_seq_length: 1024