input_file: data/gbv_cs.tsv
output_folder: outputs/sft_model

TEST_SIZE: 0.2
RANDOM_STATE: 32
use_unsloth: True
use_instruct: True
device: cuda

training_config: 
  num_epochs: 5
  learning_rate: 0.001
  batch_size: 32
  max_length: 1024
  model_name: unsloth/Llama-3.2-3B-Instruct
  # model_name: unsloth/phi-4-unsloth-bnb-4bit

lora_config: 
  r: 8
  lora_alpha: 16
  lora_dropout: 0
  task_type: CAUSAL_LM


task: evaluate_generation
task_prompt: simple-zero-shot-1
text_columns: ['gbv_text', 'cs_strategy'] 
label: ['counterspeech']


#chat_template coming from https://docs.unsloth.ai/basics/chat-templates
chat_template: llama-32 
# chat_template: phi-4
